// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactTransitionGroup = require("react-transition-group");

function make(className, $staropt$star, appear, enter, exit, children) {
  var component = $staropt$star !== undefined ? $staropt$star : "div";
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.TransitionGroup, {
              component: component,
              className: className,
              appear: appear,
              enter: enter,
              exit: exit
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
